language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly-2017-09-29

env:
  global:
    - CLIPPY_VERSION=0.0.165
    - secure: "fqkXSf3MbpAnfM9FhZKClaFzRA/4AheFwQlf1bFKQIkYmL5rr+D9HbQRHpEhAyvXnpKLx0guRXjlhBGuhwAQUXzFk5VMS5egg41gXBSMDWKJrfwILd0rS4YW3YOFSmwQCo5r5pDsFgkmZpvdSgYr3ZnMrVu560FFhQFdYJViV3f/DYgMKjrNbvKfEgSd6cp/NLRldJCnv5zdkBksXaaLiMkYoxgFjpWvxFG5nk35GGJ1Yk6Q+KyxcGO4TR+6gyKcMwSJrAyFaD6RyDh3bjNDYFxb95R6LKewr53pBHGiZWYT6l2UcI1NPJXTx31L95b49cvR1z3sO3Hvkj5RHMLQz+O8J/ZQkmYMdzTe8nfx+U9ecesxz1dyI7Z50oLEQh+JEfHf3yXy+cTySaKzZX92tljY+BxjcYxGJjIEH3RRnfG4vE/cBEIC8EkENVUSyf/sLUMs1YtADA6xopGCMZ6d2ZDcs3lIeLVwbcJCs0SDmHdDP57oZ4Kb+0iyfjgCamT7N98W9/M/S0ATk5dEmyvCCT+VompKvcXjsRIIL5fuwUaZBrf2jbXgcLz7cfS2CUhw0EYvdIc2wrSqctpJB+Daz9mtR0B2lLT/93cIN/C/QT6ke9ghNb6Thq+TYa7+cjtiFkOCHR+nDwdmQtp2sIGumCeXbR+y7X4KMjraLgCuXic="

before_script:
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo install clippy --vers $CLIPPY_VERSION --force;
    esac

script:
  - cargo test
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo clippy -- -D warnings;
    esac

before_deploy:
  - cargo package

deploy:
  provider: script
  script: cargo publish --verbose --token "$CRATES_IO_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
