[package]
name = "multiaddr"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]

base58 = { path = "../base58" }
multihash = { path = "../multihash" }
varint = { path = "../varint" }
