[package]
name = "maddr"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]
error-chain = "0.5.0"
mhash = { git = "https://github.com/mycorrhiza/mhash-rs" }
varmint = "0.1.2"
